[package]
name = "transaction_constructor"
version = "0.1.0"
edition = "2021"

[dependencies]
# Argument parsing
clap = { version = "4.0", features = ["derive"] }

# Logging
log = "0.4"
env_logger = "0.10"

# Async runtime
tokio = { version = "1", features = ["full"] }

# Networking and bindings
tonic = "0.10"
openssl = "0.10"
openssl-sys = "0.9"
solana-sdk = "1.17"
crossbeam-channel = "0.5"
dashmap = "5.5"
builder_block = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
