[package]
name = "transaction_constructor"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.10"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
tonic = "0.10"
openssl = "0.10"
openssl-sys = "0.9"
solana-sdk = "1.17"
crossbeam-channel = "0.5"
dashmap = "5.5"
builder_block = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
